FROM mysql:latest

# RUN cp /etc/mysql/conf.d/source/* /etc/mysql/conf.d/

# RUN chown mysql:mysql /etc/mysql/conf.d/mysql.cnf
# RUN chmod 600 /etc/mysql/conf.d/mysql.cnf

# RUN chmod 644 '/etc/mysql/conf.d/mysql.cnf'
# RUN chmod 644 '/etc/mysql/conf.d/mysqld_charset.cnf'

